-
    name: "es_diagnosis_alarm_pro_offline_index_${CITY_ID}"
    host: "${ES2307}"
    uri: "/_sql"
    params: "select count(*) from cn_diagnosis_alarm_pro_offline_index where dt in('${YESTERDAY}') and cityid=${CITY_ID} limit 1"
    method: "post"
    func: "check_es"
    desc: "${CITY_NAME}_cn_diagnosis_alarm_pro_offline_index_离线数据"
    group: "es_cn_diagnosis_alarm_pro_offline_index"
    monitor_key: "monitor_api_es_diagnosis_pro_${CITY_ID}"
    monitor_interval: 960
    time_slot:
      -
          start_time: "08:00:00"
          end_time: "21:00:00"
    assert_true:
      -
          actual: "$.hits.total"
          assert: "<="
          expected: 0
          err_desc: "数据量为空"
