-
    name: "es_junction_hour_report_${CITY_ID}"
    host: "${ES2307}"
    uri: "/_sql"
    params: "select count(*) from cn_junction_hour_report where dt in('${YESTERDAY}') and cityid=${CITY_ID} limit 1"
    method: "post"
    func: "check_es"
    desc: "${CITY_NAME}_cn_junction_hour_report_离线数据"
    group: "es_cn_junction_hour_report"
    monitor_key: "monitor_api_es_junction_hour_${CITY_ID}"
    monitor_interval: 960
    time_slot:
      -
        start_time: "08:00:00"
        end_time: "21:00:00"
    assert_true:
      -
        actual: "$.hits.total"
        assert: "<="
        expected: 0
        err_desc: "数据量为空"
