-
    name: "online_its_alarm_junction_month_${CITY_ID}"
    host: "${ES2307}"
    uri: "/_sql"
    params: "select count(*) from online_its_alarm_junction_month where date in('${YESTERDAY}') and city_id=${CITY_ID} limit 1"
    func: "check_es"
    method: "post"
    desc: "${CITY_NAME}_online_its_alarm_junction_month_离线数据"
    group: "es_online_its_alarm_junction_month"
    monitor_key: "monitor_api_es_junction_month_${CITY_ID}"
    monitor_interval: 100
    time_slot:
      -
        start_time: "08:00:00"
        end_time: "21:00:00"

    assert_true:
      -
        actual: "$.hits.total"
        assert: "<="
        expected: 0
        err_desc: "数据量为空"
