-
    host: "100.90.165.32"
    port: "8088"
    group: "itstool"
    monitor_key: "monitor_telnet_100.90.165.32:8088"

-
    host: "100.90.163.51"
    port: "8000"
    group: "itstool"
    monitor_key: "monitor_telnet_100.90.163.51:8000"

-
    host: "100.90.163.52"
    port: "8000"
    group: "itstool"
    monitor_key: "monitor_telnet_100.90.163.51:8000"

-
    host: "10.183.232.145"
    port: "8886"
    group: "its-mobile"
    monitor_key: "monitor_telnet_10.183.232.145:8886"

-
    host: "10.183.240.177"
    port: "8886"
    group: "its-mobile"
    monitor_key: "monitor_telnet_10.183.240.177:8886"

-
    host: "10.183.236.177"
    port: "8886"
    group: "its-mobile"
    monitor_key: "monitor_telnet_10.183.236.177:8886"
