-
    host: "100.90.165.26"
    port: "8000"
    monitor_interval: 100
    group: "signal-map-data(php接口)"
    monitor_key: "monitor_telnet_100.90.165.26:8000"

-
    host: "100.90.227.60"
    port: "8000"
    monitor_interval: 100
    group: "signal-map-data(php接口)"
    monitor_key: "monitor_telnet_100.90.227.60:8000"

-
    host: "100.90.163.51"
    port: "8173"
    monitor_interval: 50
    group: "signal-api"
    monitor_key: "monitor_telnet_100.90.163.51:8173"

-
    host: "100.90.163.52"
    port: "8173"
    monitor_interval: 50
    group: "signal-api"
    monitor_key: "monitor_telnet_100.90.163.52:8173"

-
    host: "10.85.128.81"
    port: "30357"
    monitor_interval: 100
    group: "signal-control"
    monitor_key: "monitor_telnet_10.85.128.81:30357"

-
    host: "100.90.163.51"
    port: "8071"
    group: "signal-gateway"
    monitor_key: "monitor_telnet_100.90.163.51:8071"

-
    host: "100.90.163.52"
    port: "8071"
    group: "signal-gateway"
    monitor_key: "monitor_telnet_100.90.163.52:8071"

-
    host: "100.90.163.51"
    port: "8076"
    group: "signal-passport"
    monitor_key: "monitor_telnet_100.90.163.51:8076"

-
    host: "100.90.163.51"
    port: "8099"
    group: "signal-data-service"
    monitor_key: "monitor_telnet_100.90.163.51:8099"

-
    host: "100.90.163.52"
    port: "8099"
    group: "signal-data-service"
    monitor_key: "monitor_telnet_100.90.163.52:8099"